Ext.define('Ext.Praxis.model.sales.InterlineAnalysis.GridData2', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'A2159CCUST', type: 'string'},
        {name: 'A2159TKT', type: 'string'},
        {name: 'A2159SEQ', type: 'string'},
        {name: 'A2159TKTI', type: 'string'},
        {name: 'A2159CPN', type: 'int'},
        {name: 'A2159CNJ', type: 'string'},
        {name: 'A2159FUENT', type: 'string'},
        {name: 'A2159FPROC', type: 'string'},
        {name: 'A2159FEVTA', type: 'string'},
        {name: 'A2159AGENT', type: 'string'},
        {name: 'A2159PSVTA', type: 'string'},
        {name: 'A2159CIVTA', type: 'string'},
        {name: 'A2159CUR', type: 'string'},
        {name: 'A2159FARE', type: 'float'},
        {name: 'A2159MILLA', type: 'int'},
        {name: 'A2159ORIG', type: 'string'},
        {name: 'A2159DEST', type: 'string'},
        {name: 'A2159RUTA', type: 'string'},
        {name: 'A2159CARRM', type: 'string'},
        {name: 'A2159CARRO', type: 'string'},
        {name: 'A2159NVLO', type: 'string'},
        {name: 'A2159FVLO', type: 'string'},
        {name: 'A2159CLASE', type: 'string'},
        {name: 'A2159FBASI', type: 'string'},
        {name: 'A2159FAREC', type: 'float'},
        {name: 'A2159PRFAR', type: 'float'},
        {name: 'A2159MILLC', type: 'int'},
        {name: 'A2159PRMIL', type: 'float'},
        {name: 'A2159FOAL', type: 'string'},
        {name: 'A2159RVMIL', type: 'float'},
        {name: 'A2159VAL', type: 'float'},
        {name: 'A2159PRDIF', type: 'float'},
        {name: 'A2159DIFF', type: 'float'},
        {name: 'CARR_DES', type: 'string'}
    ]
});