    Ext.define('Ext.Praxis.model.sales.DeterminationOfCommission.GridData', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'A2845FECVT', type: 'string'},
        {name: 'A2845CIAI', type: 'string'},
        {name: 'A2845CUPON', type: 'string'},
        {name: 'A2845TRNCU', type: 'string'},
        {name: 'A2845AGENT', type: 'string'},
        {name: 'A2845IATAH', type: 'string'},
        {name: 'A2845FUENT', type: 'string'},
        {name: 'A2845PAIVT', type: 'string'},
        {name: 'A2845CODAC', type: 'string'},
        {name: 'A2845VRSAC', type: 'string'},
        {name: 'A2845VALOL', type: 'string'},
        {name: 'A2845MDAFA', type: 'string'},
        {name: 'A2845PORCO', type: 'string'},
        {name: 'A2845TTCOM', type: 'string'},
        {name: 'A2845POUPF', type: 'string'},
        {name: 'A2845VUPFR', type: 'string'},
        {name: 'A2845TAGRF', type: 'string'},
        
        {name: 'A2650FPROC', type: 'string'},
        {name: 'A720CIAI', type: 'string'},
        {name: 'A720FORMAI', type: 'string'},
        {name: 'A720SERIEI', type: 'string'},
        {name: 'A2650GRUPO', type: 'string'},
        {name: 'A720AGENTE', type: 'string'},
        {name: 'A2650FUENT', type: 'string'},
        {name: 'A720PAIVTA', type: 'string'},
        {name: 'A720MDAFA', type: 'string'},
        {name: 'A720FARE', type: 'string'},
        {name: 'A720MDARV', type: 'string'},
        {name: 'A720FARERV', type: 'string'},
        {name: 'A720MDACOM', type: 'string'},
        {name: 'A720TTCOMM', type: 'string'},
        {name: 'A720PORCOM', type: 'string'},
        {name: 'A720MDACM', type: 'string'},
        {name: 'A720TTSCMM', type: 'string'},
        {name: 'A720PORSCM', type: 'string'},
        {name: 'A2650CODAC', type: 'string'},
        {name: 'A2650VRSAC', type: 'string'},
        {name: 'A2650PUPFR', type: 'string'},
        {name: 'A2650VUPFR', type: 'string'},
        {name: 'A2650POVCO', type: 'string'},
        {name: 'A2650VOVCO', type: 'string'},
        {name: 'A2650PTOCO', type: 'string'},
        {name: 'A2650VTOCO', type: 'string'},
        {name: 'DIFFA', type: 'string'},
        {name: 'DIFFB', type: 'string'},
        {name: 'DIFFB', type: 'string'},
//        {name: 'A2650PUPFR', type: 'string'},
        {name: 'A2650CDERR', type: 'string'},
        {name: 'A2650TAGRF', type: 'string'}
    ]
});