Ext.define('Ext.Praxis.model.flown.Item.GridData', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'RN', type: 'string'},
        {name: 'AIRCODE', type: 'string'},
        {name: 'AIRNAME', type: 'string'},
        {name: 'TICKET', type: 'string'},
        {name: 'CUPON', type: 'string'},
        {name: 'SEQ', type: 'string'},
        {name: 'DFLIGHT', type: 'string'},
        {name: 'NFLIGHT', type: 'string'},
        {name: 'CARR', type: 'string'},
        {name: 'ORI', type: 'string'},
        {name: 'DES', type: 'string'},
        {name: 'AMOUREV', type: 'string'},
        {name: 'TCREV', type: 'string'},
        {name: 'AMOULOC', type: 'string'},
        {name: 'CTACONT', type: 'string'},
        {name: 'CTA', type: 'string'},
        {name: 'SUBCTA', type: 'string'},
        {name: 'PERIODO', type: 'string'},
        {name: 'TITULO', type: 'string'},
        {name: 'TIPOING', type: 'string'},
        {name: 'ITEM', type: 'string'},
        {name: 'CLASOD', type: 'string'},
        {name: 'TIDOCOD', type: 'string'},
        {name: 'TITRANOD', type: 'string'},
        {name: 'VOLINVOL', type: 'string'},
        {name: 'RUTAOD', type: 'string'},
        {name: 'BASEGRAOD', type: 'string'},
        {name: 'IVAOD', type: 'string'},
        {name: 'OD', type: 'string'},
        {name: 'CNXOD', type: 'string'},
        {name: 'TASAOD2', type: 'string'},
        {name: 'BASEGRAOD2', type: 'string'},
        {name: 'IVAOD2', type: 'string'},
        {name: 'CURRLOCVT', type: 'string'},
        {name: 'RUTFCALVT', type: 'string'},
        {name: 'TARIFALOC', type: 'string'},
        {name: 'YQLOCVT', type: 'string'},
        {name: 'IVAVTA', type: 'string'},
        {name: 'BASEGRAVT', type: 'string'},
        {name: 'TASAIVAVT', type: 'string'},
        {name: 'ODFCALVT', type: 'string'},
        {name: 'RUTFCALOD', type: 'string'},
        {name: 'CNXIR', type: 'string'},
        {name: 'TASAOD', type: 'string'}
        
    ]
});