Ext.define('Ext.Praxis.view.payments.DataIntegrityForm.Filters', {
    extend: 'Ext.form.Panel',
    alias: 'widget.' + prototype.id + '-filters',
    border: true,
    bodyStyle: 'background-color: #E3EAF9;',
    padding: '2px 0px 1px 0px',
    layout: 'column',
    items: [
        {
            xtype: 'panel',
            border: false,
            bodyStyle: 'background: transparent',
            height: 'auto',
            margin: '0 0 0 0 ',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'form',
                    padding: '2px 5px 1px 5px',
                    border: false,
                    bodyStyle: 'background: transparent',
                    margin: '0 0 0 40px',
                    layout: 'column',
                    defaults: {
//                labelStyle: 'font-weight:bold;',
                        fieldStyle: 'text-align: center;',
                        padding: '5px 1px 5px 1px',
                        anchor: '100%',
                        hiddenLabel: false,
                        labelAlign: 'right',
                        hidden: false
                    },
                    items: [
                        {
                            xtype: 'label',
                            html: '<strong style="color:#000;">Search By:</strong>',
                            align: 'left',
                            fieldStyle: 'text-align: left;',
                            padding: '8px 20px 0px 5px',
                            hidden: false
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateSel',
                            triggerAction: 'all',
                            enableKeyEvents: true,
                            readOnly: false,
                            editable: true,
                            valueField: 'code',
                            displayField: 'name',
                            fieldStyle: 'text-align: left;',
                            width: 100,
                            hidden: false
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateFromYear',
                            fieldLabel: 'From',
                            labelAlign: 'right',
                            queryMode: 'local',
                            editable: false,
                            triggerAction: 'all',
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: false,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            labelWidth: 60,
                            width: 150,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateFromMonth',
                            labelAlign: 'right',
                            queryMode: 'local',
                            triggerAction: 'all',
                            editable: false,
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: false,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            width: 70,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateFromDay',
                            labelAlign: 'right',
                            queryMode: 'local',
                            triggerAction: 'all',
                            editable: false,
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: true,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            width: 70,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateToYear',
                            fieldLabel: 'To',
                            labelAlign: 'right',
                            queryMode: 'local',
                            editable: false,
                            triggerAction: 'all',
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: false,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            labelWidth: 60,
                            width: 150,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateToMonth',
                            labelAlign: 'right',
                            queryMode: 'local',
                            triggerAction: 'all',
                            editable: false,
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: false,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            width: 70,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            id: prototype.id + '-cmbDateToDay',
                            labelAlign: 'right',
                            queryMode: 'local',
                            triggerAction: 'all',
                            editable: false,
                            autoSelect: false,
                            enableKeyEvents: true,
                            caseSensitive: true,
                            hidden: true,
                            valueField: 'code',
                            displayField: 'name',
                            emptyText: 'All',
                            width: 70,
                            anchor: '100%'
                        },
                        {
                            xtype: 'combo',
                            fieldLabel: '<strong style="color:red;font-size:13px;"></strong>  Credit Card Code',
                            id: prototype.id + '-cmbCode',
                            disabled: false,
                            width: 300,
                            labelWidth: 120,
                            queryMode: 'local',
                            triggerAction: 'all',
                            valueField: 'CODE',
                            displayField: 'NAME',
                            hidden: false,
                            hiddenLabel: false
                        }
                        ,
                        {
                            xtype: 'combo',
                            fieldLabel: 'Currency ',
                            id: prototype.id + '-cmbCurrency',
                            queryMode: 'local',
                            triggerAction: 'all',
                            valueField: 'A005KEY',
                            displayField: 'A005KEY2',
                            emptyText: 'All',
                            //maxLength:3,
                            labelWidth: 80,
                            width: 300,
                            hidden: false,
                            hiddenLabel: false
                        }
                        ,
                        {
                            xtype: 'combo',
                            fieldLabel: '<strong style="color:red;font-size:13px;"></strong>  Country',
                            id: prototype.id + '-cmbCountry',
                            queryMode: 'local',
                            triggerAction: 'all',
                            valueField: 'A006PAIS',
                            displayField: 'A006NOMBRE',
                            width: 300,
                            anyMatch: false,
                            labelWidth: 80,
                            hidden: false,
                            hiddenLabel: false,
                            margin: '0 40 0 0',
                        },
                        {
                            xtype: 'label',
                            html: '<strong style="color:#000;">Merchant:</strong>',
                            align: 'left',
                            fieldStyle: 'text-align: left;',
                            padding: '8px 20px 0px 5px',
                            hidden: false
                        },
                        {
                            xtype: 'textfield',
                            id: prototype.id + '-txtMERCHN',
                            enableKeyEvents: true,
                            caseSensitive: true,
                            allowBlank: true,
                            readOnly: false,
                            editable: true,
                            enforceMaxLength: true,
                            maxLength: 20,
                            maskRe: /[0-9]/,
                            labelWidth: 120,
                            width: 130,
                            hidden: false,
                            hiddenLabel: false,
                            listeners: {
                                keypress: 'eventKey'
                            }
                        },
                    ]
                },
            ]
        }
    ]
});
