# To change this template, choose Tools | Templates
# and open the template in the editor.

log4j.rootLogger = DEBUG, CONSOLE, FILE_INFO, FILE_ERROR

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Target=System.out
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%n%d{yyyy-MM-dd HH:mm:ss} [%t] %-4r [%-5p] [%l] %n%m%n

log4j.appender.FILE_ERROR=org.apache.log4j.RollingFileAppender
log4j.appender.FILE_ERROR.Threshold=ERROR
log4j.appender.FILE_ERROR.ImmediateFlush=true
log4j.appender.FILE_ERROR.File=C:\\Applications\\PRAXIS\\LOG\\Log4jAEROMEXICO_ERROR.log
log4j.appender.FILE_ERROR.Append=true
log4j.appender.FILE_ERROR.MaxFileSize=150MB
log4j.appender.FILE_ERROR.MaxBackupIndex=5
log4j.appender.FILE_ERROR.DatePattern='.'yyyy-MM-dd
log4j.appender.FILE_ERROR.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE_ERROR.layout.ConversionPattern=%n%d{yyyy-MM-dd HH:mm:ss} [%t] %-4r [%-5p] [%l] %n%m%n

log4j.appender.FILE_INFO=org.apache.log4j.RollingFileAppender
log4j.appender.FILE_INFO.Threshold=INFO
log4j.appender.FILE_INFO.ImmediateFlush=true
log4j.appender.FILE_INFO.File=C:\\Applications\\PRAXIS\\LOG\\Log4jAEROMEXICO_ERROR.log
log4j.appender.FILE_INFO.Append=true
log4j.appender.FILE_INFO.MaxFileSize=150MB
log4j.appender.FILE_INFO.MaxBackupIndex=5
log4j.appender.FILE_INFO.DatePattern='.'yyyy-MM-dd
log4j.appender.FILE_INFO.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE_INFO.layout.ConversionPattern=%n%d{yyyy-MM-dd HH:mm:ss} [%t] %-4r [%-5p] [%l] %n%m%n

log4j.rootCategory=ERROR,CONSOLE
#log4j.category.org.springframework=ERROR
log4j.logger.errorLog=ALL,FILE_ERROR,CONSOLE
log4j.logger.infoLog=ALL,FILE_INFO,CONSOLE
