Ext.define('Ext.Praxis.view.payments.InputsCatalogForm.Filters', {
    extend: 'Ext.form.Panel',
    alias: 'widget.' + prototype.id + '-filters',
    border: true,
    bodyStyle: 'background-color: #E3EAF9;',
    padding: '8px 118px 1px 118px',
    layout: 'column',
    items: [
        {
            id: prototype.id + '-Filters',
            xtype: 'form',
            border: false,
            bodyStyle: 'background: transparent',
            padding: '2px 5px 1px 5px',
            layout: 'column',
            defaults: {
//                labelStyle: 'font-weight:bold;',
                fieldStyle: 'text-align: center;',
                padding: '5px 1px 5px 1px',
                anchor: '100%',
                hiddenLabel: false,
                labelAlign: 'right',
                hidden: false
            },
            items: [
                {xtype: 'tbspacer', width: 10},
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbSTATUS',
                    fieldLabel: 'Status',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 60,
                    width: 150,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbFASE',
                    fieldLabel: 'Phase',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 60,
                    width: 150,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbINPTYPE',
                    fieldLabel: 'Type',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 60,
                    width: 200,
                    anchor: '100%'
                },
                {xtype: 'tbspacer', width: 20},
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbINPEXTE',
                    fieldLabel: 'Extension',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 60,
                    width: 150,
                    anchor: '100%'
                },
                {xtype: 'tbspacer', width: 20},
                {
                    xtype: 'label',
                    text: 'Input Name:',
                    padding: '8px 1px 2px 1px',
                    width: 80,
                },
                {
                    xtype: 'textfield',
                    id: prototype.id + '-txtINPName',
                    fieldStyle: 'text-align:center',
                    enforceMaxLength: true,
                    maskRe: /[a-zA-Z]/,
                    maxLength: 30,
                    width: 150,
                    enableKeyEvents: true,
                    listeners: {
                        keypress: 'filterINPName'
                    }
                },
            ]
        }
    ]
});
