ORA_user=mflor
ORA_pwd=mflor
ORA_url=jdbc\:oracle\:thin\:@10.0.0.73\:1521\:dbmia
ORA_driver=oracle.jdbc.driver.OracleDriver
ORA_initial=5
ORA_maximum=7
IS_user=USRCWR
IS_pwd=W01RE01
IS_url=jdbc:as400://10.19.17.25/PRAXIS;translate-binary=true;
IS_driver=com.ibm.as400.access.AS400JDBCDriver
IS_initial=2
IS_maximum=3