Ext.define('Ext.Praxis.view.payments.ChargebackForm.Filters', {
    extend: 'Ext.form.Panel',
    alias: 'widget.' + prototype.id + '-filters',
    border: true,
    bodyStyle: 'background-color: #E3EAF9;',
    padding: '2px 0px 1px 0px',
    layout: 'column',
    items: [
        {
            xtype: 'form',
            id: prototype.id + '-contFilter',
            border: false,
            bodyStyle: 'background: transparent',
            padding: '2px 5px 1px 5px',
            layout: 'column',
            defaults: {
                labelStyle: 'font-weight:bold;',
                fieldStyle: 'text-align: center;',
                padding: '5px 1px 5px 1px',
                anchor: '100%',
                hiddenLabel: false,
                labelAlign: 'right',
                hidden: false
            },
            items: [
                {xtype: 'tbspacer', width: 100},
                {
                    xtype: 'label',
                    text: 'Search By:',
                    padding: '8 0 0 0',
                    width: 65
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbFecFiltro',
                    queryMode: 'local',
                    allowBlank: false,
                    forceSelection: true,
                    selectOnFocus: true,
                    caseSensitive: false,
                    autoSelect: true,
                    editable: true,
                    width: 150,
                    value: "CHGDATE",
                    typeAhead: true,
                    valueField: 'code',
                    displayField: 'name',
                    listConfig: {minWidth: 130},
                    enableKeyEvents: true,
                    triggerAction: 'all',
                    listeners: {
                    }
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateFromYear',
                    fieldLabel: 'From',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 50,
                    width: 130,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateFromMonth',
                    labelAlign: 'right',
                    queryMode: 'local',
                    triggerAction: 'all',
                    editable: false,
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    width: 60,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateFromDay',
                    queryMode: 'local',
                    triggerAction: 'all',
                    editable: false,
                    autoSelect: true,
                    enableKeyEvents: true,
                    forceSelection: true,
                    caseSensitive: false,
                    valueField: 'code', displayField: 'name',
                    emptyText: 'All',
                    width: 60,
                    typeAhead: true,
                    listeners: {
                        change: 'onFromDayChange',
                        keypress: 'onTextKeypress'
                    }
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateToYear',
                    fieldLabel: 'To',
                    labelAlign: 'right',
                    queryMode: 'local',
                    editable: false,
                    triggerAction: 'all',
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    labelWidth: 50,
                    width: 130,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateToMonth',
                    labelAlign: 'right',
                    queryMode: 'local',
                    triggerAction: 'all',
                    editable: false,
                    autoSelect: false,
                    enableKeyEvents: true,
                    caseSensitive: true,
                    hidden: false,
                    valueField: 'code',
                    displayField: 'name',
                    emptyText: 'All',
                    width: 60,
                    anchor: '100%'
                },
                {
                    xtype: 'combo',
                    id: prototype.id + '-cmbDateToDay',
                    queryMode: 'local',
                    triggerAction: 'all',
                    editable: false,
                    autoSelect: true,
                    enableKeyEvents: true,
                    forceSelection: true,
                    caseSensitive: false,
                    valueField: 'code', displayField: 'name',
                    emptyText: 'All',
                    width: 60,
                    typeAhead: true,
                    listeners: {
                        change: 'onToDayChange',
                        keypress: 'onTextKeypress'
                    }
                },
                {
                    xtype: 'combo',
                    fieldLabel: 'Source Code',
                    id: prototype.id + '-cmbIN_FTE',
                    fieldStyle: 'text-align: left;',
                    queryMode: 'local',
                    editable: false,
                    valueField: 'code',
                    hidden:true,
                    displayField: 'name',
                    labelWidth: 110,
                    width: 220
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Auth. Code:',
                    id: prototype.id + '-txtSAUTHOC',
                    allowBlank: true,
//                    maskRe: /[0-9]/,
                    enforceMaxLength: true,
                    maxLength: 6,
                    labelWidth: 100,
                    width: 210,
//                    hidden:true,
                    enableKeyEvents: true,
                    listeners: {
                        keypress: 'eventKey'
                    }
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Merchant Nbr.:',
                    id: prototype.id + '-txtMERCHN',
                    allowBlank: true,
                    maskRe: /[0-9]/,
                    enforceMaxLength: true,
                    maxLength: 10,
                    labelWidth: 130,
                    width: 250,
//                    hidden:true,
                    enableKeyEvents: true,
                    listeners: {
                        keypress: 'eventKey'
                    }
                },
                {
                    xtype: 'combo',
                    fieldLabel: 'Status',
                    id: prototype.id + '-cmbSTATT',
                    fieldStyle: 'text-align: left;',
                    queryMode: 'local',
                    editable: false,
                    valueField: 'code',
                    hidden:true,
                    displayField: 'name',
                    labelWidth: 80,
                    width: 270
                }
            ]
        }
    ]
});
