package net.miatech.praxis.payment.entities;

import lombok.Data;

/**
 *
 * @author dvicente
 */
@Data
public class MPF090 {
    private String CCUST,PRDA,CODPRO,CCUSTPRO,FLIQUIDACI,FECVTA,HORAVTA,LIQUIDACIO,
            MERCHAND,NMERCHAND,TRANSTYPE,SCARCOD,TERMINAL,OPERACION,TDOM,SCARDN,ARN,SAUTHOC,PAIS,
            MONEDA,FREFER,PNR,IATA,TICKET,NARCHIVO,
            VALDATE,BANDOC,DATECI,TRANCI,ADATE,ACCCOMP,FSELEC,FECSELEC,USCR,FECR,HOCR,PGMCR,USUP,FEUP,HOUP,
            PGMUP,PLANP,STATUS,CODERR,CUENTA,CORE,CODE,CODEBANK,BANKCM,SOCIETY,SOCIETYL,BANKCUR,
            TIPOARCH,FTRANSFER,MONEDAPAGO,SEQDELI;
    
    private Double IMPORTE,COMISION,IMPORTECA,COMISIONCA,AJUSTES,NETO,IVACOM,DEVISV,FEEMTO,AJCOMI,IVAJCM,RETIVA,RETREN,COMTIN,
            IVAPER,MULTAS,RETRDB,REICOM,IVATIN,OTHRIM,IMPORTEPAG;
    
    private Integer NUMCUOTA,TOTCUOTA;
    
    private String DESC_PRO;
}
