package net.miatech.praxis.payment.entities;

import lombok.Data;

/**
 *
 * @author dvicente
 */
@Data
public class MPF060 {
    private String CCUST,TDOC,STVAL,SCOUNTRY,FTE,SDATE,SAGENT,NEGOC,MERCHAND,SUCMERCH,SPNR,
            PRDA,TRAN,ADATE,VALDATE,TIPOTAR,SCARCOD,SCARDN,SCARDNCOR,SAUTHOC,SDATEXP,SOCIETY,CODEBANK,
            COREP,CODPRO,CCUSTPRO,SOCIETYL,BANDOC,SEQ,TERMI,STCON,FCONT,ACCNUMBER,RED,CCIA,FORMA,SERIE,DATEF,
            FREGLA,SCURRENCY,FLOAD,LDATE,TDATE,SORIG,REASONREJ,RECORDSTS,BSTVAL,BDATEP,BAID,
            SDATE1,SAUTHOC1,SCARCOD1,FLOADE,LDATEE,EMISOR,STATUSC,SDATEC,DATEC,TRANC,DATECI,
            TRANCI,DATET,STATT,DATEL,HORAL,CCNCFT,CCNTRN,CERROIN,CERROR,CANAL,FSELEC,FECSELEC,UAUDIT,FUNDSTRGR,FUNDSTRGK,
            CHARNBR,STVALCHG,ORDERID,LIQUIDACIO,MONEDAPAGO,USCR,FECR,HOCR,PGMCR,USUP,FEUP,HOUP,PGMUP;
    
    private Integer QTYTKT,QTYDOC;
    private Double SVFOP,IVA,PROPINA,TOTAL,COMISION,COMISTOTA,BASEFUE,RTEFUE,RTEIVA,BASICA,RTEICA,
            NETO,NETOEECC,FAREO,SVFOPC,SVFOPD,IVAC,PROPINAC,COMISIOC,BASEFUEC,RTEFUEC,RTEIVAC,BASICAC,RTEICAC,NETOC,
            FAREC,FAREDIFFC,COMMFAREC,COMMDIFFC,ADMTOTAL,RATECOM,COMISION1,IMPORTEPAG;
    
    //OTROS CAMPOS
    private String DESC_PRO;
}
